# Generated by Django 4.1.3 on 2022-11-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestatus',
            old_name='n_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='messagestatus',
            old_name='n_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='messagestatus',
            old_name='n_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='messagestatus',
            old_name='n_user',
            new_name='user',
        ),
    ]
