# Generated by Django 4.1.3 on 2022-11-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_n_content_messagestatus_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MessageStatus',
        ),
    ]
